import { StyleSheet, Platform, StatusBar } from 'react-native'
import {
    hs,
    vs,
    getFontSize,
    MIN_TOUCH_SIZE,
} from '@/libs/utils'
import { Colors } from '@/libs/constants/theme'

export const createStyles = (theme: 'light' | 'dark') => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors[theme].backgroundSecondary,
    },
    content: {
        flex: 1,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: vs(10),
        fontSize: getFontSize(16),
        color: Colors[theme].textSecondary,
        lineHeight: getFontSize(22),
    },
    profileSection: {
        backgroundColor: Colors[theme].surface,
        alignItems: 'center',
        paddingVertical: vs(40),
        paddingHorizontal: hs(20),
        marginBottom: vs(20),
        borderBottomLeftRadius: hs(24),
        borderBottomRightRadius: hs(24),
    },
    avatarContainer: {
        position: 'relative',
        marginBottom: vs(20),
    },
    avatar: {
        width: hs(110),
        height: hs(110),
        borderRadius: hs(55),
        borderWidth: hs(4),
        borderColor: Colors[theme].primary,
    },
    editButton: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: Colors[theme].primary,
        borderRadius: hs(18),
        width: hs(36),
        height: hs(36),
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 3,
        borderColor: Colors[theme].surface,
        elevation: 4,
        shadowColor: Colors[theme].primary,
        shadowOffset: { width: 0, height: vs(2) },
        shadowOpacity: 0.3,
        shadowRadius: hs(4),
    },
    userName: {
        fontSize: getFontSize(24),
        fontWeight: '700',
        color: Colors[theme].text,
        marginBottom: vs(6),
        lineHeight: getFontSize(30),
    },
    userEmail: {
        fontSize: getFontSize(14),
        color: Colors[theme].textSecondary,
        lineHeight: getFontSize(20),
        marginBottom: vs(4),
    },
    userPhone: {
        fontSize: getFontSize(14),
        color: Colors[theme].textSecondary,
        lineHeight: getFontSize(20),
    },
    section: {
        backgroundColor: Colors[theme].surface,
        marginHorizontal: hs(16),
        borderRadius: hs(16),
        marginBottom: vs(16),
        overflow: 'hidden',
        elevation: 2,
        shadowColor: Colors[theme].shadowColor,
        shadowOffset: { width: 0, height: vs(2) },
        shadowOpacity: 0.08,
        shadowRadius: hs(8),
        borderWidth: 1,
        borderColor: Colors[theme].border,
    },
    lastSection: {
        marginBottom: vs(30),
    },
    optionRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: hs(20),
        paddingVertical: vs(16),
        minHeight: MIN_TOUCH_SIZE,
        borderBottomWidth: 1,
        borderBottomColor: Colors[theme].border,
    },
    optionLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    optionTitle: {
        fontSize: getFontSize(15),
        color: Colors[theme].text,
        marginLeft: hs(15),
        lineHeight: getFontSize(22),
        fontWeight: '500',
    },
    optionRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    optionValue: {
        fontSize: getFontSize(14),
        color: Colors[theme].textSecondary,
        marginRight: hs(10),
        fontWeight: '500',
        lineHeight: getFontSize(20),
    },
    statusBarSpacer: {
        height: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    bottomSpacer: {
        height: vs(20),
    },
})
