import { StyleSheet } from 'react-native'
import {
    hs,
    vs,
    getFontSize,
    MIN_TOUCH_SIZE,
} from '@/libs/utils'
import {
    Colors,
    Typography,
    Spacing,
    BorderRadius,
} from '@/libs/constants/theme'

export const createStyles = (theme: 'light' | 'dark') => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors[theme].backgroundSecondary,
    },
    headerBar: {
        backgroundColor: Colors[theme].surface,
        borderBottomWidth: 1,
        borderBottomColor: Colors[theme].border,
        elevation: 2,
    },
    topHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: hs(Spacing.lg),
        paddingVertical: vs(Spacing.sm),
        justifyContent: 'space-between',
    },
    backButtonContainer: {
        padding: hs(Spacing.xs),
        width: hs(40),
        minHeight: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    groupNameContainer: {
        flex: 1,
        alignItems: 'center',
    },
    groupName: {
        fontSize: getFontSize(Typography.h3.fontSize),
        fontWeight: Typography.h3.fontWeight,
        color: Colors[theme].text,
        lineHeight: getFontSize(Typography.h3.lineHeight),
    },
    headerRight: {
        flexDirection: 'row',
    },
    headerIcon: {
        padding: hs(Spacing.xs),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    tabBar: {
        flexDirection: 'row',
        backgroundColor: Colors[theme].surface,
        borderBottomWidth: 1,
        borderBottomColor: Colors[theme].border,
    },
    tabContainer: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: vs(Spacing.md),
        minHeight: MIN_TOUCH_SIZE,
        justifyContent: 'center',
    },
    tabText: {
        fontSize: getFontSize(Typography.bodyLarge.fontSize),
        color: Colors[theme].textSecondary,
        fontWeight: Typography.labelMedium.fontWeight,
        lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
    },
    activeTabContainer: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: vs(Spacing.md),
        position: 'relative',
        minHeight: MIN_TOUCH_SIZE,
        justifyContent: 'center',
    },
    activeTabText: {
        fontSize: getFontSize(Typography.bodyLarge.fontSize),
        color: Colors[theme].primary,
        fontWeight: Typography.h4.fontWeight,
        lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
    },
    activeTabIndicator: {
        position: 'absolute',
        bottom: 0,
        height: vs(3),
        width: '100%',
        backgroundColor: Colors[theme].primary,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: hs(32),
    },
    emptyIconContainer: {
        position: 'relative',
        marginBottom: vs(Spacing.xxl),
        width: hs(200),
        height: vs(150),
        justifyContent: 'center',
        alignItems: 'center',
    },
    fileIcons: {
        position: 'absolute',
        width: '100%',
        height: '100%',
    },
    floatingIcon1: {
        position: 'absolute',
        left: hs(Spacing.xl),
        top: vs(Spacing.xl),
        transform: [{ rotate: '-15deg' }],
    },
    floatingIcon2: {
        position: 'absolute',
        right: hs(Spacing.xl),
        top: vs(30),
        transform: [{ rotate: '15deg' }],
    },
    emptyTitle: {
        fontSize: getFontSize(Typography.h3.fontSize),
        fontWeight: Typography.h3.fontWeight,
        color: Colors[theme].text,
        textAlign: 'center',
        marginBottom: vs(Spacing.md),
        lineHeight: getFontSize(Typography.h3.lineHeight),
    },
    emptySubtitle: {
        fontSize: getFontSize(Typography.bodyMedium.fontSize),
        color: Colors[theme].textSecondary,
        textAlign: 'center',
        lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
    },
    listContainer: {
        padding: hs(Spacing.lg),
    },
    materialItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors[theme].surface,
        padding: hs(Spacing.md),
        borderRadius: hs(BorderRadius.md),
        marginBottom: vs(Spacing.md),
        elevation: 1,
        shadowColor: Colors[theme].shadowColor,
        shadowOffset: { width: 0, height: vs(1) },
        shadowOpacity: 0.1,
        shadowRadius: hs(2),
    },
    fileIconContainer: {
        marginRight: hs(Spacing.md),
    },
    fileInfo: {
        flex: 1,
    },
    fileName: {
        fontSize: getFontSize(Typography.h4.fontSize),
        fontWeight: Typography.h4.fontWeight,
        color: Colors[theme].text,
        marginBottom: vs(Spacing.xs),
        lineHeight: getFontSize(Typography.h4.lineHeight),
    },
    fileDetails: {
        fontSize: getFontSize(Typography.bodySmall.fontSize),
        color: Colors[theme].textSecondary,
        marginBottom: vs(2),
        lineHeight: getFontSize(Typography.bodySmall.lineHeight),
    },
    fileDate: {
        fontSize: getFontSize(Typography.caption.fontSize),
        color: Colors[theme].textTertiary,
        lineHeight: getFontSize(Typography.caption.lineHeight),
    },
    moreButton: {
        padding: hs(Spacing.xs),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
})
