import { StyleSheet } from 'react-native'
import {
    hs,
    vs,
    getFontSize,
    MIN_TOUCH_SIZE,
} from '@/libs/utils'

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    headerBar: {
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        elevation: 2,
    },
    topHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: hs(16),
        paddingVertical: vs(8),
        justifyContent: 'space-between',
    },
    backButtonContainer: {
        padding: hs(4),
        width: hs(40),
        minHeight: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    groupNameContainer: {
        flex: 1,
        alignItems: 'center',
    },
    groupName: {
        fontSize: getFontSize(18),
        fontWeight: '600',
        color: '#000',
        lineHeight: getFontSize(24),
    },
    headerRight: {
        flexDirection: 'row',
    },
    headerIcon: {
        padding: hs(4),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    tabBar: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    tabContainer: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: vs(12),
        minHeight: MIN_TOUCH_SIZE,
        justifyContent: 'center',
    },
    tabText: {
        fontSize: getFontSize(16),
        color: '#666',
        fontWeight: '500',
        lineHeight: getFontSize(22),
    },
    activeTabContainer: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: vs(12),
        position: 'relative',
        minHeight: MIN_TOUCH_SIZE,
        justifyContent: 'center',
    },
    activeTabText: {
        fontSize: getFontSize(16),
        color: '#0078d4',
        fontWeight: '600',
        lineHeight: getFontSize(22),
    },
    activeTabIndicator: {
        position: 'absolute',
        bottom: 0,
        height: vs(3),
        width: '100%',
        backgroundColor: '#0078d4',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: hs(32),
    },
    emptyIconContainer: {
        position: 'relative',
        marginBottom: vs(24),
        width: hs(200),
        height: vs(150),
        justifyContent: 'center',
        alignItems: 'center',
    },
    fileIcons: {
        position: 'absolute',
        width: '100%',
        height: '100%',
    },
    floatingIcon1: {
        position: 'absolute',
        left: hs(20),
        top: vs(20),
        transform: [{ rotate: '-15deg' }],
    },
    floatingIcon2: {
        position: 'absolute',
        right: hs(20),
        top: vs(30),
        transform: [{ rotate: '15deg' }],
    },
    emptyTitle: {
        fontSize: getFontSize(18),
        fontWeight: '600',
        color: '#000',
        textAlign: 'center',
        marginBottom: vs(12),
        lineHeight: getFontSize(24),
    },
    emptySubtitle: {
        fontSize: getFontSize(14),
        color: '#666',
        textAlign: 'center',
        lineHeight: getFontSize(20),
    },
    listContainer: {
        padding: hs(16),
    },
    materialItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        padding: hs(12),
        borderRadius: hs(8),
        marginBottom: vs(12),
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: vs(1) },
        shadowOpacity: 0.1,
        shadowRadius: hs(2),
    },
    fileIconContainer: {
        marginRight: hs(12),
    },
    fileInfo: {
        flex: 1,
    },
    fileName: {
        fontSize: getFontSize(16),
        fontWeight: '600',
        color: '#000',
        marginBottom: vs(4),
        lineHeight: getFontSize(22),
    },
    fileDetails: {
        fontSize: getFontSize(13),
        color: '#666',
        marginBottom: vs(2),
        lineHeight: getFontSize(18),
    },
    fileDate: {
        fontSize: getFontSize(12),
        color: '#999',
        lineHeight: getFontSize(16),
    },
    moreButton: {
        padding: hs(4),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
})
