import { StyleSheet } from 'react-native'
import {
    hs,
    vs,
    getFontSize,
    MIN_TOUCH_SIZE,
} from '@/libs/utils'

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: hs(16),
        paddingVertical: vs(12),
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    backButton: {
        padding: hs(8),
        marginRight: hs(8),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerContent: {
        flex: 1,
    },
    headerTitle: {
        fontSize: getFontSize(16),
        fontWeight: '600',
        color: '#333',
        lineHeight: getFontSize(22),
    },
    headerSubtitle: {
        fontSize: getFontSize(12),
        color: '#6b7280',
        marginTop: vs(2),
        lineHeight: getFontSize(16),
    },
    moreButton: {
        padding: hs(8),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    keyboardContainer: {
        flex: 1,
    },
    scrollContainer: {
        flex: 1,
    },
    postContent: {
        backgroundColor: '#fff',
        margin: hs(16),
        padding: hs(16),
        borderRadius: hs(8),
    },
    userSection: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: vs(16),
    },
    avatarPlaceholder: {
        width: hs(40),
        height: hs(40),
        borderRadius: hs(20),
        backgroundColor: '#AD2D7A',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: hs(12),
    },
    avatarText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: getFontSize(16),
    },
    userInfo: {
        flex: 1,
    },
    userName: {
        fontSize: getFontSize(16),
        fontWeight: '600',
        color: '#333',
        marginBottom: vs(2),
        lineHeight: getFontSize(22),
    },
    date: {
        fontSize: getFontSize(12),
        color: '#6b7280',
        lineHeight: getFontSize(16),
    },
    postTitle: {
        fontSize: getFontSize(18),
        fontWeight: 'bold',
        color: '#333',
        marginBottom: vs(12),
        lineHeight: getFontSize(24),
    },
    postText: {
        fontSize: getFontSize(16),
        lineHeight: getFontSize(22),
        color: '#333',
        marginBottom: vs(16),
    },
    linkButton: {
        backgroundColor: '#E0E7FF',
        padding: hs(12),
        borderRadius: hs(8),
        alignSelf: 'flex-start',
        marginBottom: vs(16),
    },
    linkText: {
        color: '#3B82F6',
        fontWeight: '500',
        fontSize: getFontSize(14),
        lineHeight: getFontSize(20),
    },
    actionButtons: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingVertical: vs(8),
    },
    actionButton: {
        padding: hs(8),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    commentsSection: {
        marginTop: vs(8),
        backgroundColor: '#fff',
    },
    commentsSectionHeader: {
        paddingHorizontal: hs(16),
        paddingVertical: vs(12),
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
    },
    commentsSectionTitle: {
        fontSize: getFontSize(16),
        fontWeight: '600',
        color: '#333',
        lineHeight: getFontSize(22),
    },
    noCommentsContainer: {
        alignItems: 'center',
        paddingVertical: vs(40),
        paddingHorizontal: hs(20),
    },
    noCommentsText: {
        fontSize: getFontSize(16),
        fontWeight: '500',
        color: '#9ca3af',
        marginTop: vs(12),
        lineHeight: getFontSize(22),
    },
    noCommentsSubtext: {
        fontSize: getFontSize(14),
        color: '#d1d5db',
        marginTop: vs(4),
        lineHeight: getFontSize(20),
    },
    commentInputContainer: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        paddingHorizontal: hs(16),
        paddingVertical: vs(12),
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#e5e7eb',
    },
    commentInputWrapper: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'flex-end',
        backgroundColor: '#f3f4f6',
        borderRadius: hs(20),
        paddingHorizontal: hs(12),
        paddingVertical: vs(8),
        marginRight: hs(8),
    },
    addButton: {
        marginRight: hs(8),
        padding: hs(2),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    commentInput: {
        flex: 1,
        fontSize: getFontSize(14),
        maxHeight: vs(100),
        paddingVertical: vs(4),
        color: '#333',
    },
    emojiButton: {
        marginLeft: hs(8),
        padding: hs(2),
    },
    cameraButton: {
        marginLeft: hs(8),
        padding: hs(2),
    },
    micButton: {
        marginLeft: hs(8),
        padding: hs(2),
    },
    sendButton: {
        backgroundColor: '#f3f4f6',
        borderRadius: hs(20),
        padding: hs(8),
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
    },
    sendButtonDisabled: {
        opacity: 0.5,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
})
