import { StyleSheet } from 'react-native'
import {
    hs,
    vs,
    getFontSize,
    MIN_TOUCH_SIZE,
} from '@/libs/utils'
import {
    Colors,
    Typography,
    Spacing,
    BorderRadius,
    Palette,
} from '@/libs/constants/theme'

export const createStyles = (theme: 'light' | 'dark') => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors[theme].background,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: hs(Spacing.lg),
        paddingVertical: vs(Spacing.md),
        backgroundColor: Colors[theme].surface,
        borderBottomWidth: 1,
        borderBottomColor: Colors[theme].border,
    },
    backButton: {
        padding: hs(Spacing.sm),
        marginRight: hs(Spacing.sm),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerContent: {
        flex: 1,
    },
    headerTitle: {
        fontSize: getFontSize(Typography.h4.fontSize),
        fontWeight: Typography.h4.fontWeight,
        color: Colors[theme].text,
        lineHeight: getFontSize(Typography.h4.lineHeight),
    },
    headerSubtitle: {
        fontSize: getFontSize(Typography.caption.fontSize),
        color: Colors[theme].textSecondary,
        marginTop: vs(2),
        lineHeight: getFontSize(Typography.caption.lineHeight),
    },
    moreButton: {
        padding: hs(Spacing.sm),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    keyboardContainer: {
        flex: 1,
    },
    scrollContainer: {
        flex: 1,
    },
    postContent: {
        backgroundColor: Colors[theme].surface,
        margin: hs(Spacing.lg),
        padding: hs(Spacing.lg),
        borderRadius: hs(BorderRadius.md),
    },
    userSection: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: vs(Spacing.lg),
    },
    avatarPlaceholder: {
        width: hs(40),
        height: hs(40),
        borderRadius: hs(20),
        backgroundColor: Palette.brand[700],
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: hs(Spacing.md),
    },
    avatarText: {
        color: Colors[theme].textInverse,
        fontWeight: Typography.h4.fontWeight,
        fontSize: getFontSize(Typography.h4.fontSize),
    },
    userInfo: {
        flex: 1,
    },
    userName: {
        fontSize: getFontSize(Typography.h4.fontSize),
        fontWeight: Typography.h4.fontWeight,
        color: Colors[theme].text,
        marginBottom: vs(2),
        lineHeight: getFontSize(Typography.h4.lineHeight),
    },
    date: {
        fontSize: getFontSize(Typography.caption.fontSize),
        color: Colors[theme].textSecondary,
        lineHeight: getFontSize(Typography.caption.lineHeight),
    },
    postTitle: {
        fontSize: getFontSize(Typography.h3.fontSize),
        fontWeight: Typography.h3.fontWeight,
        color: Colors[theme].text,
        marginBottom: vs(Spacing.md),
        lineHeight: getFontSize(Typography.h3.lineHeight),
    },
    postText: {
        fontSize: getFontSize(Typography.bodyLarge.fontSize),
        lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
        color: Colors[theme].text,
        marginBottom: vs(Spacing.lg),
    },
    linkButton: {
        backgroundColor: Palette.brand[50],
        padding: hs(Spacing.md),
        borderRadius: hs(BorderRadius.md),
        alignSelf: 'flex-start',
        marginBottom: vs(Spacing.lg),
    },
    linkText: {
        color: Colors[theme].info,
        fontWeight: Typography.labelMedium.fontWeight,
        fontSize: getFontSize(Typography.bodyMedium.fontSize),
        lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
    },
    actionButtons: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingVertical: vs(Spacing.sm),
    },
    actionButton: {
        padding: hs(Spacing.sm),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    commentsSection: {
        marginTop: vs(Spacing.sm),
        backgroundColor: Colors[theme].surface,
    },
    commentsSectionHeader: {
        paddingHorizontal: hs(Spacing.lg),
        paddingVertical: vs(Spacing.md),
        borderBottomWidth: 1,
        borderBottomColor: Colors[theme].border,
    },
    commentsSectionTitle: {
        fontSize: getFontSize(Typography.h4.fontSize),
        fontWeight: Typography.h4.fontWeight,
        color: Colors[theme].text,
        lineHeight: getFontSize(Typography.h4.lineHeight),
    },
    noCommentsContainer: {
        alignItems: 'center',
        paddingVertical: vs(40),
        paddingHorizontal: hs(Spacing.xl),
    },
    noCommentsText: {
        fontSize: getFontSize(Typography.bodyLarge.fontSize),
        fontWeight: Typography.labelMedium.fontWeight,
        color: Colors[theme].textTertiary,
        marginTop: vs(Spacing.md),
        lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
    },
    noCommentsSubtext: {
        fontSize: getFontSize(Typography.bodyMedium.fontSize),
        color: Colors[theme].textDisabled,
        marginTop: vs(Spacing.xs),
        lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
    },
    commentInputContainer: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        paddingHorizontal: hs(Spacing.lg),
        paddingVertical: vs(Spacing.md),
        backgroundColor: Colors[theme].surface,
        borderTopWidth: 1,
        borderTopColor: Colors[theme].border,
    },
    commentInputWrapper: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors[theme].inputBackground,
        borderRadius: hs(20),
        paddingHorizontal: hs(Spacing.md),
        paddingVertical: vs(Spacing.sm),
        marginRight: hs(Spacing.sm),
    },
    addButton: {
        marginRight: hs(Spacing.sm),
        padding: hs(2),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    commentInput: {
        flex: 1,
        fontSize: getFontSize(Typography.bodyMedium.fontSize),
        maxHeight: vs(100),
        paddingVertical: vs(Spacing.xs),
        color: Colors[theme].inputText,
    },
    emojiButton: {
        marginLeft: hs(Spacing.sm),
        padding: hs(2),
    },
    cameraButton: {
        marginLeft: hs(Spacing.sm),
        padding: hs(2),
    },
    micButton: {
        marginLeft: hs(Spacing.sm),
        padding: hs(2),
    },
    sendButton: {
        backgroundColor: Colors[theme].inputBackground,
        borderRadius: hs(20),
        padding: hs(Spacing.sm),
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
    },
    sendButtonDisabled: {
        opacity: 0.5,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    // Material styles
    materialsSection: {
        marginTop: vs(Spacing.lg),
        paddingTop: vs(Spacing.md),
        borderTopWidth: 1,
        borderTopColor: Colors[theme].border,
    },
    materialsSectionTitle: {
        fontSize: getFontSize(Typography.h4.fontSize),
        fontWeight: Typography.h4.fontWeight,
        color: Colors[theme].text,
        marginBottom: vs(Spacing.md),
        lineHeight: getFontSize(Typography.h4.lineHeight),
    },
    materialItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors[theme].backgroundSecondary,
        padding: hs(Spacing.md),
        borderRadius: hs(BorderRadius.md),
        marginBottom: vs(Spacing.sm),
    },
    materialIconContainer: {
        marginRight: hs(Spacing.md),
    },
    materialInfo: {
        flex: 1,
    },
    materialFileName: {
        fontSize: getFontSize(Typography.bodyLarge.fontSize),
        fontWeight: Typography.labelMedium.fontWeight,
        color: Colors[theme].text,
        marginBottom: vs(2),
        lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
    },
    materialFileDetails: {
        fontSize: getFontSize(Typography.caption.fontSize),
        color: Colors[theme].textSecondary,
        marginBottom: vs(2),
        lineHeight: getFontSize(Typography.caption.lineHeight),
    },
    materialFileDate: {
        fontSize: getFontSize(Typography.caption.fontSize),
        color: Colors[theme].textTertiary,
        lineHeight: getFontSize(Typography.caption.lineHeight),
    },
    materialMoreButton: {
        padding: hs(Spacing.xs),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
})
