import { StyleSheet } from 'react-native'
import {
    hs,
    vs,
    getFontSize,
    MIN_TOUCH_SIZE,
} from '@/libs/utils'
import {
    Colors,
    Typography,
    Spacing,
    BorderRadius,
    Palette,
} from '@/libs/constants/theme'

export const createStyles = (theme: 'light' | 'dark') => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors[theme].backgroundSecondary,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: hs(Spacing.lg),
        paddingVertical: vs(Spacing.md),
        backgroundColor: Colors[theme].surface,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: Colors[theme].border,
    },
    skipButton: {
        padding: hs(Spacing.sm),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    skipText: {
        fontSize: getFontSize(Typography.labelLarge.fontSize),
        color: Colors[theme].primary,
        lineHeight: getFontSize(Typography.labelLarge.lineHeight),
    },
    headerCenter: {
        alignItems: 'center',
        flex: 1,
    },
    headerTitle: {
        fontSize: getFontSize(Typography.h3.fontSize),
        fontWeight: Typography.h3.fontWeight,
        color: Colors[theme].text,
        lineHeight: getFontSize(Typography.h3.lineHeight),
    },
    teamCode: {
        fontSize: getFontSize(Typography.caption.fontSize),
        color: Colors[theme].textSecondary,
        marginTop: vs(2),
        lineHeight: getFontSize(Typography.caption.lineHeight),
    },
    doneButton: {
        padding: hs(Spacing.sm),
        minWidth: hs(50),
        alignItems: 'flex-end',
        minHeight: MIN_TOUCH_SIZE,
        justifyContent: 'center',
    },
    doneText: {
        fontSize: getFontSize(Typography.labelLarge.fontSize),
        color: Colors[theme].primary,
        fontWeight: Typography.labelLarge.fontWeight,
        lineHeight: getFontSize(Typography.labelLarge.lineHeight),
    },
    disabledButton: {
        opacity: 0.6,
    },
    tabBar: {
        flexDirection: 'row',
        backgroundColor: Colors[theme].surface,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: Colors[theme].border,
    },
    tab: {
        flex: 1,
        paddingVertical: vs(Spacing.md),
        alignItems: 'center',
        borderBottomWidth: 2,
        borderBottomColor: 'transparent',
        minHeight: MIN_TOUCH_SIZE,
        justifyContent: 'center',
    },
    activeTab: {
        borderBottomColor: Colors[theme].primary,
    },
    tabText: {
        fontSize: getFontSize(Typography.bodyLarge.fontSize),
        color: Colors[theme].textSecondary,
        lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
    },
    activeTabText: {
        color: Colors[theme].primary,
        fontWeight: Typography.labelLarge.fontWeight,
    },
    searchSection: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: hs(Spacing.lg),
        paddingVertical: vs(Spacing.md),
        backgroundColor: Colors[theme].surface,
    },
    searchLabel: {
        fontSize: getFontSize(Typography.bodyLarge.fontSize),
        color: Colors[theme].text,
        marginRight: hs(Spacing.sm),
        lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
    },
    searchInput: {
        flex: 1,
        fontSize: getFontSize(Typography.bodyLarge.fontSize),
        color: Colors[theme].inputText,
        paddingVertical: vs(Spacing.sm),
        minHeight: MIN_TOUCH_SIZE,
    },
    content: {
        flex: 1,
        padding: hs(Spacing.lg),
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: vs(Spacing.md),
        fontSize: getFontSize(Typography.bodyMedium.fontSize),
        color: Colors[theme].textSecondary,
        lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    emptyText: {
        marginTop: vs(Spacing.md),
        fontSize: getFontSize(Typography.bodyLarge.fontSize),
        color: Colors[theme].textTertiary,
        lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
    },
    sectionTitle: {
        fontSize: getFontSize(Typography.caption.fontSize),
        color: Colors[theme].textSecondary,
        fontWeight: Typography.labelMedium.fontWeight,
        marginBottom: vs(Spacing.lg),
        letterSpacing: 1,
        lineHeight: getFontSize(Typography.caption.lineHeight),
    },
    membersList: {
        flex: 1,
    },
    memberItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: vs(Spacing.md),
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: Colors[theme].border,
        minHeight: MIN_TOUCH_SIZE,
    },
    memberInfo: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
    memberAvatar: {
        width: hs(48),
        height: hs(48),
        borderRadius: hs(24),
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: hs(Spacing.md),
    },
    memberAvatarText: {
        fontSize: getFontSize(Typography.h2.fontSize),
        fontWeight: Typography.labelLarge.fontWeight,
        color: Colors[theme].textInverse,
    },
    memberDetails: {
        flex: 1,
    },
    memberName: {
        fontSize: getFontSize(Typography.h4.fontSize),
        fontWeight: Typography.h4.fontWeight,
        color: Colors[theme].text,
        marginBottom: vs(4),
        lineHeight: getFontSize(Typography.h4.lineHeight),
    },
    memberRole: {
        fontSize: getFontSize(Typography.bodyMedium.fontSize),
        color: Colors[theme].textSecondary,
        lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
    },
    addButton: {
        padding: hs(Spacing.sm),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    selectedCounter: {
        paddingHorizontal: hs(Spacing.lg),
        paddingVertical: vs(Spacing.sm),
        backgroundColor: Palette.brand[50],
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: Colors[theme].border,
    },
    selectedCounterText: {
        fontSize: getFontSize(Typography.bodyMedium.fontSize),
        color: Colors[theme].primary,
        fontWeight: Typography.labelMedium.fontWeight,
        lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
    },
})
