import { StyleSheet } from 'react-native'
import {
    hs,
    vs,
    getFontSize,
    MIN_TOUCH_SIZE,
} from '@/libs/utils'
import {
    Colors,
    Typography,
    Spacing,
    BorderRadius,
    Palette,
} from '@/libs/constants/theme'

export const createStyles = (theme: 'light' | 'dark') => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors[theme].background,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: hs(Spacing.lg),
        paddingVertical: vs(Spacing.md),
        borderBottomWidth: 1,
        borderBottomColor: Colors[theme].border,
    },
    headerTitle: {
        fontSize: getFontSize(Typography.h3.fontSize),
        fontWeight: Typography.h3.fontWeight,
        flex: 1,
        textAlign: 'center',
        lineHeight: getFontSize(Typography.h3.lineHeight),
        color: Colors[theme].text,
    },
    scrollView: {
        flex: 1,
    },
    descriptionSection: {
        paddingHorizontal: hs(Spacing.lg),
        paddingTop: vs(Spacing.xl),
    },
    descriptionText: {
        fontSize: getFontSize(Typography.bodyMedium.fontSize),
        color: Colors[theme].textSecondary,
        lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
        marginBottom: vs(Spacing.lg),
    },
    learnMoreLink: {
        fontSize: getFontSize(Typography.bodyMedium.fontSize),
        color: Colors[theme].primary,
        fontWeight: Typography.labelMedium.fontWeight,
        lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
    },
    teamNameSection: {
        marginTop: vs(Spacing.sectionGap),
        paddingHorizontal: hs(Spacing.lg),
    },
    teamNameLabel: {
        fontSize: getFontSize(Typography.h4.fontSize),
        fontWeight: Typography.h4.fontWeight,
        marginBottom: vs(Spacing.sm),
        lineHeight: getFontSize(Typography.h4.lineHeight),
        color: Colors[theme].text,
    },
    codeBox: {
        backgroundColor: Colors[theme].backgroundSecondary,
        paddingHorizontal: hs(Spacing.md),
        paddingVertical: vs(10),
        borderRadius: hs(BorderRadius.md),
        marginBottom: vs(Spacing.lg),
    },
    codeText: {
        fontSize: getFontSize(Typography.bodyMedium.fontSize),
        color: Colors[theme].textTertiary,
        lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
    },
    optionsMenu: {
        marginTop: vs(Spacing.sectionGap),
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: hs(Spacing.lg),
        paddingVertical: vs(Spacing.lg),
        borderBottomWidth: 1,
        borderBottomColor: Colors[theme].border,
        minHeight: MIN_TOUCH_SIZE,
    },
    menuContent: {
        flex: 1,
        marginLeft: hs(Spacing.md),
    },
    menuTitle: {
        fontSize: getFontSize(Typography.h4.fontSize),
        fontWeight: Typography.labelMedium.fontWeight,
        color: Colors[theme].text,
        lineHeight: getFontSize(Typography.h4.lineHeight),
    },
    menuSubtitle: {
        fontSize: getFontSize(Typography.caption.fontSize),
        color: Colors[theme].textTertiary,
        marginTop: vs(2),
        lineHeight: getFontSize(Typography.caption.lineHeight),
    },
    actionText: {
        fontSize: getFontSize(Typography.h4.fontSize),
        fontWeight: Typography.labelMedium.fontWeight,
        color: Colors[theme].primary,
        lineHeight: getFontSize(Typography.h4.lineHeight),
    },
    actionTextMargin: {
        marginLeft: hs(Spacing.md),
    },
    menuItemWithToggle: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: hs(Spacing.lg),
        paddingVertical: vs(Spacing.lg),
        borderBottomWidth: 1,
        borderBottomColor: Colors[theme].border,
        minHeight: MIN_TOUCH_SIZE,
    },
    visibilityContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    visibilityText: {
        fontSize: getFontSize(Typography.h4.fontSize),
        fontWeight: Typography.labelMedium.fontWeight,
        color: Colors[theme].text,
        marginLeft: hs(Spacing.md),
        lineHeight: getFontSize(Typography.h4.lineHeight),
    },
    toggleSwitch: {
        width: hs(50),
        height: vs(28),
        borderRadius: hs(14),
        backgroundColor: Colors[theme].primary,
        justifyContent: 'center',
        alignItems: 'flex-end',
        paddingHorizontal: hs(2),
    },
    toggleThumb: {
        width: hs(24),
        height: hs(24),
        borderRadius: hs(12),
        backgroundColor: Colors[theme].surface,
    },
    aboutSection: {
        paddingHorizontal: hs(Spacing.lg),
        paddingTop: vs(Spacing.sectionGap),
        paddingBottom: vs(Spacing.sectionGap),
    },
    aboutTitle: {
        fontSize: getFontSize(Typography.bodyMedium.fontSize),
        fontWeight: Typography.labelMedium.fontWeight,
        color: Colors[theme].textSecondary,
        marginBottom: vs(Spacing.lg),
        lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
    },
    notificationItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: vs(Spacing.md),
    },
    notificationContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    notificationText: {
        fontSize: getFontSize(Typography.bodyLarge.fontSize),
        fontWeight: Typography.bodyLarge.fontWeight,
        color: Colors[theme].text,
        marginLeft: hs(Spacing.md),
        lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
    },
    toggleSwitchOff: {
        width: hs(50),
        height: vs(28),
        borderRadius: hs(14),
        backgroundColor: Colors[theme].borderSecondary,
        justifyContent: 'center',
        alignItems: 'flex-start',
        paddingHorizontal: hs(2),
    },
    toggleThumbOff: {
        width: hs(24),
        height: hs(24),
        borderRadius: hs(12),
        backgroundColor: Colors[theme].surface,
    },
    settingsFooter: {
        fontSize: getFontSize(Typography.caption.fontSize),
        color: Colors[theme].textTertiary,
        lineHeight: getFontSize(Typography.caption.lineHeight),
        marginTop: vs(Spacing.lg),
    },
    backButton: {
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    editButton: {
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
})
