import { StyleSheet } from 'react-native'
import {
    hs,
    vs,
    getFontSize,
    MIN_TOUCH_SIZE,
} from '@/libs/utils'
import {
    Colors,
    Typography,
    Spacing,
    BorderRadius,
} from '@/libs/constants/theme'

export const createStyles = (theme: 'light' | 'dark') => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors[theme].backgroundSecondary,
    },
    loadingContainer: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: vs(Spacing.lg),
        fontSize: getFontSize(Typography.bodyLarge.fontSize),
        color: Colors[theme].textSecondary,
        lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: hs(Spacing.lg),
        paddingVertical: vs(Spacing.md),
        paddingTop: vs(50),
        backgroundColor: Colors[theme].surface,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: Colors[theme].border,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    backButton: {
        marginRight: hs(Spacing.md),
        padding: hs(Spacing.xs),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitleContainer: {
        flex: 1,
    },
    headerTitle: {
        fontSize: getFontSize(Typography.h3.fontSize),
        fontWeight: Typography.h3.fontWeight,
        color: Colors[theme].text,
        lineHeight: getFontSize(Typography.h3.lineHeight),
    },
    headerSubtitle: {
        fontSize: getFontSize(Typography.bodyMedium.fontSize),
        color: Colors[theme].textSecondary,
        marginTop: vs(2),
        lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconButton: {
        padding: hs(Spacing.sm),
        marginLeft: hs(Spacing.xs),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    tabContainer: {
        flexDirection: 'row',
        backgroundColor: Colors[theme].surface,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: Colors[theme].border,
    },
    tab: {
        flex: 1,
        paddingVertical: vs(Spacing.lg),
        alignItems: 'center',
        borderBottomWidth: 2,
        borderBottomColor: 'transparent',
        minHeight: MIN_TOUCH_SIZE,
        justifyContent: 'center',
    },
    activeTab: {
        borderBottomColor: Colors[theme].primary,
    },
    tabText: {
        fontSize: getFontSize(Typography.bodyLarge.fontSize),
        fontWeight: Typography.labelMedium.fontWeight,
        color: Colors[theme].textSecondary,
        lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
    },
    activeTabText: {
        color: Colors[theme].primary,
        fontWeight: Typography.h4.fontWeight,
    },
    scrollView: {
        flex: 1,
    },
    memberCard: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: Colors[theme].surface,
        paddingHorizontal: hs(Spacing.lg),
        paddingVertical: vs(Spacing.md),
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: Colors[theme].border,
        minHeight: MIN_TOUCH_SIZE,
    },
    memberInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    avatar: {
        width: hs(48),
        height: hs(48),
        borderRadius: hs(24),
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: hs(Spacing.md),
        position: 'relative',
    },
    avatarImage: {
        width: hs(48),
        height: hs(48),
        borderRadius: hs(24),
    },
    avatarText: {
        color: Colors[theme].textInverse,
        fontSize: getFontSize(Typography.h3.fontSize),
        fontWeight: Typography.h3.fontWeight,
    },
    onlineIndicator: {
        position: 'absolute',
        bottom: vs(2),
        right: hs(2),
        width: hs(12),
        height: hs(12),
        borderRadius: hs(6),
        backgroundColor: Colors[theme].success,
        borderWidth: 2,
        borderColor: Colors[theme].surface,
    },
    memberDetails: {
        flex: 1,
    },
    nameContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: vs(Spacing.xs),
    },
    memberName: {
        fontSize: getFontSize(Typography.h4.fontSize),
        fontWeight: Typography.h4.fontWeight,
        color: Colors[theme].text,
        marginRight: hs(Spacing.sm),
        lineHeight: getFontSize(Typography.h4.lineHeight),
    },
    youLabel: {
        fontSize: getFontSize(Typography.caption.fontSize),
        color: Colors[theme].textSecondary,
        backgroundColor: Colors[theme].backgroundSecondary,
        paddingHorizontal: hs(6),
        paddingVertical: vs(2),
        borderRadius: hs(BorderRadius.sm),
        lineHeight: getFontSize(Typography.caption.lineHeight),
    },
    memberEmail: {
        fontSize: getFontSize(Typography.bodyMedium.fontSize),
        color: Colors[theme].textSecondary,
        lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
    },
    memberActions: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    roleLabel: {
        fontSize: getFontSize(Typography.caption.fontSize),
        color: Colors[theme].primary,
        fontWeight: Typography.labelMedium.fontWeight,
        marginRight: hs(Spacing.md),
        lineHeight: getFontSize(Typography.caption.lineHeight),
    },
    menuButton: {
        padding: hs(Spacing.sm),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: vs(60),
    },
    emptyText: {
        marginTop: vs(Spacing.lg),
        fontSize: getFontSize(Typography.bodyLarge.fontSize),
        color: Colors[theme].textSecondary,
        textAlign: 'center',
    },
})
