import { StyleSheet } from 'react-native'
import {
    hs,
    vs,
    getFontSize,
    MIN_TOUCH_SIZE,
} from '@/libs/utils'

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F5F5F5',
    },
    loadingContainer: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: vs(16),
        fontSize: getFontSize(16),
        color: '#666',
        lineHeight: getFontSize(22),
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: hs(16),
        paddingVertical: vs(12),
        paddingTop: vs(50),
        backgroundColor: '#fff',
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: '#e0e0e0',
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    backButton: {
        marginRight: hs(12),
        padding: hs(4),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitleContainer: {
        flex: 1,
    },
    headerTitle: {
        fontSize: getFontSize(18),
        fontWeight: '600',
        color: '#000',
        lineHeight: getFontSize(24),
    },
    headerSubtitle: {
        fontSize: getFontSize(14),
        color: '#666',
        marginTop: vs(2),
        lineHeight: getFontSize(20),
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconButton: {
        padding: hs(8),
        marginLeft: hs(4),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    tabContainer: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: '#e0e0e0',
    },
    tab: {
        flex: 1,
        paddingVertical: vs(16),
        alignItems: 'center',
        borderBottomWidth: 2,
        borderBottomColor: 'transparent',
        minHeight: MIN_TOUCH_SIZE,
        justifyContent: 'center',
    },
    activeTab: {
        borderBottomColor: '#0078d4',
    },
    tabText: {
        fontSize: getFontSize(16),
        fontWeight: '500',
        color: '#666',
        lineHeight: getFontSize(22),
    },
    activeTabText: {
        color: '#0078d4',
        fontWeight: '600',
    },
    scrollView: {
        flex: 1,
    },
    memberCard: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#fff',
        paddingHorizontal: hs(16),
        paddingVertical: vs(12),
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: '#e0e0e0',
        minHeight: MIN_TOUCH_SIZE,
    },
    memberInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    avatar: {
        width: hs(48),
        height: hs(48),
        borderRadius: hs(24),
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: hs(12),
        position: 'relative',
    },
    avatarImage: {
        width: hs(48),
        height: hs(48),
        borderRadius: hs(24),
    },
    avatarText: {
        color: '#fff',
        fontSize: getFontSize(18),
        fontWeight: '600',
    },
    onlineIndicator: {
        position: 'absolute',
        bottom: vs(2),
        right: hs(2),
        width: hs(12),
        height: hs(12),
        borderRadius: hs(6),
        backgroundColor: '#4CAF50',
        borderWidth: 2,
        borderColor: '#fff',
    },
    memberDetails: {
        flex: 1,
    },
    nameContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: vs(4),
    },
    memberName: {
        fontSize: getFontSize(16),
        fontWeight: '600',
        color: '#000',
        marginRight: hs(8),
        lineHeight: getFontSize(22),
    },
    youLabel: {
        fontSize: getFontSize(12),
        color: '#666',
        backgroundColor: '#F0F0F0',
        paddingHorizontal: hs(6),
        paddingVertical: vs(2),
        borderRadius: hs(4),
        lineHeight: getFontSize(16),
    },
    memberEmail: {
        fontSize: getFontSize(14),
        color: '#666',
        lineHeight: getFontSize(20),
    },
    memberActions: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    roleLabel: {
        fontSize: getFontSize(12),
        color: '#0078d4',
        fontWeight: '500',
        marginRight: hs(12),
        lineHeight: getFontSize(16),
    },
    menuButton: {
        padding: hs(8),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
})
