import { StyleSheet } from 'react-native'
import {
    hs,
    vs,
    getFontSize,
    MIN_TOUCH_SIZE,
} from '@/libs/utils'

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: hs(16),
        paddingVertical: vs(12),
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    headerTitle: {
        fontSize: getFontSize(18),
        fontWeight: '600',
        flex: 1,
        textAlign: 'center',
        lineHeight: getFontSize(24),
    },
    scrollView: {
        flex: 1,
    },
    descriptionSection: {
        paddingHorizontal: hs(16),
        paddingTop: vs(20),
    },
    descriptionText: {
        fontSize: getFontSize(14),
        color: '#666',
        lineHeight: getFontSize(22),
        marginBottom: vs(16),
    },
    learnMoreLink: {
        fontSize: getFontSize(14),
        color: '#5b5fc7',
        fontWeight: '500',
        lineHeight: getFontSize(20),
    },
    teamNameSection: {
        marginTop: vs(24),
        paddingHorizontal: hs(16),
    },
    teamNameLabel: {
        fontSize: getFontSize(16),
        fontWeight: '600',
        marginBottom: vs(8),
        lineHeight: getFontSize(22),
    },
    codeBox: {
        backgroundColor: '#f5f5f5',
        paddingHorizontal: hs(12),
        paddingVertical: vs(10),
        borderRadius: hs(8),
        marginBottom: vs(16),
    },
    codeText: {
        fontSize: getFontSize(14),
        color: '#999',
        lineHeight: getFontSize(20),
    },
    optionsMenu: {
        marginTop: vs(24),
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: hs(16),
        paddingVertical: vs(16),
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        minHeight: MIN_TOUCH_SIZE,
    },
    menuContent: {
        flex: 1,
        marginLeft: hs(12),
    },
    menuTitle: {
        fontSize: getFontSize(16),
        fontWeight: '500',
        color: '#000',
        lineHeight: getFontSize(22),
    },
    menuSubtitle: {
        fontSize: getFontSize(12),
        color: '#999',
        marginTop: vs(2),
        lineHeight: getFontSize(16),
    },
    actionText: {
        fontSize: getFontSize(16),
        fontWeight: '500',
        color: '#5b5fc7',
        lineHeight: getFontSize(22),
    },
    actionTextMargin: {
        marginLeft: hs(12),
    },
    menuItemWithToggle: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: hs(16),
        paddingVertical: vs(16),
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        minHeight: MIN_TOUCH_SIZE,
    },
    visibilityContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    visibilityText: {
        fontSize: getFontSize(16),
        fontWeight: '500',
        color: '#000',
        marginLeft: hs(12),
        lineHeight: getFontSize(22),
    },
    toggleSwitch: {
        width: hs(50),
        height: vs(28),
        borderRadius: hs(14),
        backgroundColor: '#5b5fc7',
        justifyContent: 'center',
        alignItems: 'flex-end',
        paddingHorizontal: hs(2),
    },
    toggleThumb: {
        width: hs(24),
        height: hs(24),
        borderRadius: hs(12),
        backgroundColor: '#fff',
    },
    aboutSection: {
        paddingHorizontal: hs(16),
        paddingTop: vs(24),
        paddingBottom: vs(24),
    },
    aboutTitle: {
        fontSize: getFontSize(14),
        fontWeight: '600',
        color: '#666',
        marginBottom: vs(16),
        lineHeight: getFontSize(20),
    },
    notificationItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: vs(12),
    },
    notificationContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    notificationText: {
        fontSize: getFontSize(16),
        fontWeight: '400',
        color: '#000',
        marginLeft: hs(12),
        lineHeight: getFontSize(22),
    },
    toggleSwitchOff: {
        width: hs(50),
        height: vs(28),
        borderRadius: hs(14),
        backgroundColor: '#e0e0e0',
        justifyContent: 'center',
        alignItems: 'flex-start',
        paddingHorizontal: hs(2),
    },
    toggleThumbOff: {
        width: hs(24),
        height: hs(24),
        borderRadius: hs(12),
        backgroundColor: '#fff',
    },
    settingsFooter: {
        fontSize: getFontSize(12),
        color: '#999',
        lineHeight: getFontSize(18),
        marginTop: vs(16),
    },
    backButton: {
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    editButton: {
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
})
