import { StyleSheet } from 'react-native'
import {
    hs,
    vs,
    getFontSize,
    MIN_TOUCH_SIZE,
} from '@/libs/utils'

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F5F5F5',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: hs(16),
        paddingVertical: vs(12),
        paddingTop: vs(50),
        backgroundColor: '#fff',
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    userAvatar: {
        width: hs(36),
        height: hs(36),
        borderRadius: hs(18),
        backgroundColor: '#F4E4C1',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: hs(12),
    },
    userAvatarText: {
        fontSize: getFontSize(16),
        fontWeight: '600',
        color: '#8B7355',
    },
    headerTitle: {
        fontSize: getFontSize(24),
        fontWeight: '700',
        color: '#000',
        lineHeight: getFontSize(30),
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconButton: {
        padding: hs(8),
        marginLeft: hs(4),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    aiButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f0f0ff',
        paddingHorizontal: hs(12),
        paddingVertical: vs(6),
        borderRadius: hs(16),
        marginLeft: hs(8),
        minHeight: MIN_TOUCH_SIZE,
    },
    aiButtonText: {
        fontSize: getFontSize(14),
        fontWeight: '600',
        color: '#6264a7',
        marginLeft: hs(4),
        lineHeight: getFontSize(20),
    },
    searchContainer: {
        paddingHorizontal: hs(16),
        paddingVertical: vs(12),
        backgroundColor: '#fff',
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: '#e0e0e0',
    },
    searchBar: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F2F2F7',
        paddingHorizontal: hs(12),
        paddingVertical: vs(10),
        borderRadius: hs(10),
    },
    searchPlaceholder: {
        marginLeft: hs(8),
        fontSize: getFontSize(16),
        color: '#8E8E93',
        lineHeight: getFontSize(22),
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: hs(16),
        paddingVertical: vs(12),
        backgroundColor: '#fff',
    },
    sectionTitle: {
        fontSize: getFontSize(16),
        fontWeight: '600',
        color: '#000',
        marginLeft: hs(8),
        lineHeight: getFontSize(22),
    },
    scrollView: {
        flex: 1,
    },
    generalLabel: {
        paddingLeft: hs(80),
        paddingVertical: vs(8),
        backgroundColor: '#fff',
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: '#e0e0e0',
    },
    generalText: {
        fontSize: getFontSize(14),
        color: '#8E8E93',
        lineHeight: getFontSize(20),
    },
    loadingContainer: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: vs(16),
        fontSize: getFontSize(16),
        color: '#666',
        lineHeight: getFontSize(22),
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: vs(60),
    },
    emptyText: {
        fontSize: getFontSize(18),
        fontWeight: '600',
        color: '#000',
        marginBottom: vs(8),
        lineHeight: getFontSize(24),
    },
    emptySubtext: {
        fontSize: getFontSize(14),
        color: '#666',
        marginBottom: vs(24),
        lineHeight: getFontSize(20),
    },
    createButton: {
        backgroundColor: '#0078d4',
        paddingHorizontal: hs(24),
        paddingVertical: vs(12),
        borderRadius: hs(8),
        minHeight: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    createButtonText: {
        color: '#fff',
        fontSize: getFontSize(16),
        fontWeight: '600',
        lineHeight: getFontSize(22),
    },
})
