import { StyleSheet } from 'react-native'
import {
    hs,
    vs,
    getFontSize,
    MIN_TOUCH_SIZE,
} from '@/libs/utils'
import {
    Colors,
    Typography,
    Spacing,
    BorderRadius,
    Palette,
} from '@/libs/constants/theme'

export const createStyles = (theme: 'light' | 'dark') => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors[theme].backgroundSecondary,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: hs(Spacing.lg),
        paddingVertical: vs(Spacing.md),
        backgroundColor: Colors[theme].surface,
        borderBottomWidth: 1,
        borderBottomColor: Colors[theme].border,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    userAvatar: {
        width: hs(36),
        height: hs(36),
        borderRadius: hs(18),
        backgroundColor: '#F4E4C1',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: hs(Spacing.md),
    },
    userAvatarText: {
        fontSize: getFontSize(Typography.labelLarge.fontSize),
        fontWeight: Typography.labelLarge.fontWeight,
        color: '#8B7355',
    },
    headerTitle: {
        fontSize: getFontSize(Typography.h1.fontSize),
        fontWeight: Typography.h1.fontWeight,
        color: Colors[theme].text,
        lineHeight: getFontSize(Typography.h1.lineHeight),
        letterSpacing: Typography.h1.letterSpacing,
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconButton: {
        padding: hs(Spacing.sm),
        marginLeft: hs(Spacing.xs),
        minHeight: MIN_TOUCH_SIZE,
        minWidth: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    aiButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Palette.brand[50],
        paddingHorizontal: hs(Spacing.md),
        paddingVertical: vs(6),
        borderRadius: hs(BorderRadius.xl),
        marginLeft: hs(Spacing.sm),
        minHeight: MIN_TOUCH_SIZE,
    },
    aiButtonText: {
        fontSize: getFontSize(Typography.labelMedium.fontSize),
        fontWeight: Typography.labelMedium.fontWeight,
        color: Palette.brand[600],
        marginLeft: hs(Spacing.xs),
        lineHeight: getFontSize(Typography.labelMedium.lineHeight),
        letterSpacing: Typography.labelMedium.letterSpacing,
    },
    searchContainer: {
        paddingHorizontal: hs(Spacing.lg),
        paddingVertical: vs(Spacing.md),
        backgroundColor: Colors[theme].surface,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: Colors[theme].border,
    },
    searchBar: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors[theme].inputBackground,
        paddingHorizontal: hs(Spacing.md),
        paddingVertical: vs(10),
        borderRadius: hs(10),
    },
    searchPlaceholder: {
        marginLeft: hs(Spacing.sm),
        fontSize: getFontSize(Typography.bodyLarge.fontSize),
        color: Colors[theme].textTertiary,
        lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: hs(Spacing.lg),
        paddingVertical: vs(Spacing.md),
        backgroundColor: Colors[theme].surface,
    },
    sectionTitle: {
        fontSize: getFontSize(Typography.h4.fontSize),
        fontWeight: Typography.h4.fontWeight,
        color: Colors[theme].text,
        marginLeft: hs(Spacing.sm),
        lineHeight: getFontSize(Typography.h4.lineHeight),
        letterSpacing: Typography.h4.letterSpacing,
    },
    scrollView: {
        flex: 1,
    },
    generalLabel: {
        paddingLeft: hs(80),
        paddingVertical: vs(Spacing.sm),
        backgroundColor: Colors[theme].surface,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: Colors[theme].border,
    },
    generalText: {
        fontSize: getFontSize(Typography.bodyMedium.fontSize),
        fontWeight: Typography.bodyMedium.fontWeight,
        color: Colors[theme].textTertiary,
        lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
    },
    loadingContainer: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: vs(Spacing.lg),
        fontSize: getFontSize(Typography.bodyLarge.fontSize),
        fontWeight: Typography.bodyLarge.fontWeight,
        color: Colors[theme].textSecondary,
        lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: vs(60),
    },
    emptyText: {
        fontSize: getFontSize(Typography.h3.fontSize),
        fontWeight: Typography.h3.fontWeight,
        color: Colors[theme].text,
        marginBottom: vs(Spacing.sm),
        lineHeight: getFontSize(Typography.h3.lineHeight),
        letterSpacing: Typography.h3.letterSpacing,
    },
    emptySubtext: {
        fontSize: getFontSize(Typography.bodyMedium.fontSize),
        fontWeight: Typography.bodyMedium.fontWeight,
        color: Colors[theme].textSecondary,
        marginBottom: vs(Spacing.sectionGap),
        lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
    },
    createButton: {
        backgroundColor: Colors[theme].buttonPrimary,
        paddingHorizontal: hs(Spacing.sectionGap),
        paddingVertical: vs(Spacing.md),
        borderRadius: hs(BorderRadius.md),
        minHeight: MIN_TOUCH_SIZE,
        justifyContent: 'center',
        alignItems: 'center',
    },
    createButtonText: {
        color: Colors[theme].buttonPrimaryText,
        fontSize: getFontSize(Typography.button.fontSize),
        fontWeight: Typography.button.fontWeight,
        lineHeight: getFontSize(Typography.button.lineHeight),
        letterSpacing: Typography.button.letterSpacing,
    },
})
