import { StyleSheet } from 'react-native'
import {
  wp,
  hp,
  vs,
  hs,
  getSafePadding,
  getFontSize,
  MIN_TOUCH_SIZE,
} from '@/libs/utils'
import { Colors, Typography, Spacing, BorderRadius } from '@/libs/constants/theme'

export const createStyles = (theme: 'light' | 'dark') => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors[theme].backgroundSecondary,
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: getSafePadding(),
    paddingVertical: vs(20),
    minHeight: hp(100),
  },
  card: {
    backgroundColor: Colors[theme].surface,
    borderRadius: hs(BorderRadius.xl),
    paddingHorizontal: getSafePadding(),
    paddingVertical: vs(Spacing.xxl),
    shadowColor: Colors[theme].shadowColor,
    shadowOffset: {
      width: 0,
      height: vs(2),
    },
    shadowOpacity: 0.1,
    shadowRadius: hs(8),
    elevation: 5,
    width: '100%',
    maxWidth: wp(90),
    alignSelf: 'center',
  },
  title: {
    fontSize: getFontSize(Typography.h2.fontSize),
    fontWeight: Typography.h2.fontWeight as '600',
    color: Colors[theme].text,
    textAlign: 'center',
    marginBottom: vs(Spacing.md),
    lineHeight: getFontSize(Typography.h2.lineHeight),
    letterSpacing: Typography.h2.letterSpacing,
  },
  subtitle: {
    fontSize: getFontSize(Typography.bodyMedium.fontSize),
    color: Colors[theme].textTertiary,
    textAlign: 'center',
    marginBottom: vs(Spacing.xxl),
    lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
    paddingHorizontal: hs(Spacing.sm),
  },
  formGroup: {
    marginBottom: vs(Spacing.xxl),
  },
  label: {
    fontSize: getFontSize(Typography.labelMedium.fontSize),
    fontWeight: Typography.labelMedium.fontWeight as '500',
    color: Colors[theme].textSecondary,
    marginBottom: vs(Spacing.sm),
    lineHeight: getFontSize(Typography.labelMedium.lineHeight),
    letterSpacing: Typography.labelMedium.letterSpacing,
  },
  input: {
    backgroundColor: Colors[theme].inputBackground,
    borderRadius: hs(BorderRadius.md),
    paddingHorizontal: hs(Spacing.lg),
    paddingVertical: vs(Spacing.md),
    fontSize: getFontSize(Typography.bodyLarge.fontSize),
    color: Colors[theme].text,
    borderWidth: 1,
    borderColor: Colors[theme].border,
    minHeight: Math.max(MIN_TOUCH_SIZE, vs(48)),
    textAlignVertical: 'center',
    lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
  },
  button: {
    backgroundColor: Colors[theme].buttonPrimary,
    borderRadius: hs(BorderRadius.md),
    paddingVertical: vs(14),
    alignItems: 'center',
    marginBottom: vs(Spacing.lg),
    minHeight: Math.max(MIN_TOUCH_SIZE, vs(48)),
    justifyContent: 'center',
  },
  buttonDisabled: {
    backgroundColor: Colors[theme].buttonPrimaryDisabled,
  },
  buttonText: {
    color: Colors[theme].buttonPrimaryText,
    fontSize: getFontSize(Typography.button.fontSize),
    fontWeight: Typography.button.fontWeight as '600',
    lineHeight: getFontSize(Typography.button.lineHeight),
    letterSpacing: Typography.button.letterSpacing,
  },
  backButton: {
    alignItems: 'center',
    paddingVertical: vs(Spacing.md),
    minHeight: MIN_TOUCH_SIZE,
    justifyContent: 'center',
  },
  backButtonText: {
    fontSize: getFontSize(Typography.labelMedium.fontSize),
    color: Colors[theme].link,
    fontWeight: Typography.labelMedium.fontWeight as '500',
    lineHeight: getFontSize(Typography.labelMedium.lineHeight),
    letterSpacing: Typography.labelMedium.letterSpacing,
  },
})
