import { StyleSheet } from 'react-native'
import {
  wp,
  hp,
  hs,
  vs,
  getSafePadding,
  getFontSize,
  MIN_TOUCH_SIZE,
} from '@/libs/utils'
import { Colors, Typography, Spacing, BorderRadius } from '@/libs/constants/theme'

export const createStyles = (theme: 'light' | 'dark') => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors[theme].backgroundSecondary,
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: getSafePadding(),
    paddingVertical: vs(20),
    minHeight: hp(100),
  },
  loginCard: {
    backgroundColor: Colors[theme].surface,
    borderRadius: hs(BorderRadius.xl),
    paddingHorizontal: getSafePadding(),
    paddingVertical: vs(Spacing.xxl),
    shadowColor: Colors[theme].shadowColor,
    shadowOffset: {
      width: 0,
      height: vs(2),
    },
    shadowOpacity: 0.1,
    shadowRadius: hs(8),
    elevation: 5,
    width: '100%',
    maxWidth: wp(90),
    alignSelf: 'center',
  },
  title: {
    fontSize: getFontSize(Typography.h2.fontSize),
    fontWeight: Typography.h2.fontWeight as '600',
    color: Colors[theme].text,
    textAlign: 'center',
    marginBottom: vs(Spacing.xxl),
    lineHeight: getFontSize(Typography.h2.lineHeight),
    letterSpacing: Typography.h2.letterSpacing,
  },
  formGroup: {
    marginBottom: vs(Spacing.lg),
  },
  label: {
    fontSize: getFontSize(Typography.labelMedium.fontSize),
    fontWeight: Typography.labelMedium.fontWeight as '500',
    color: Colors[theme].textSecondary,
    marginBottom: vs(Spacing.sm),
    lineHeight: getFontSize(Typography.labelMedium.lineHeight),
    letterSpacing: Typography.labelMedium.letterSpacing,
  },
  input: {
    backgroundColor: Colors[theme].inputBackground,
    borderRadius: hs(BorderRadius.md),
    paddingHorizontal: hs(Spacing.lg),
    paddingVertical: vs(Spacing.md),
    fontSize: getFontSize(Typography.bodyLarge.fontSize),
    color: Colors[theme].inputText,
    borderWidth: 1,
    borderColor: Colors[theme].inputBorder,
    minHeight: Math.max(MIN_TOUCH_SIZE, vs(48)),
    textAlignVertical: 'center',
    lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors[theme].inputBackground,
    borderRadius: hs(BorderRadius.md),
    borderWidth: 1,
    borderColor: Colors[theme].inputBorder,
    minHeight: Math.max(MIN_TOUCH_SIZE, vs(48)),
  },
  passwordInput: {
    flex: 1,
    paddingHorizontal: hs(Spacing.lg),
    paddingVertical: vs(Spacing.md),
    fontSize: getFontSize(Typography.bodyLarge.fontSize),
    color: Colors[theme].inputText,
    textAlignVertical: 'center',
    lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
  },
  eyeIcon: {
    paddingHorizontal: hs(Spacing.md),
    paddingVertical: vs(Spacing.sm),
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: MIN_TOUCH_SIZE,
    minHeight: MIN_TOUCH_SIZE,
  },
  optionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: vs(Spacing.xxl),
    minHeight: MIN_TOUCH_SIZE,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingVertical: vs(8),
  },
  checkbox: {
    width: hs(18),
    height: hs(18),
    borderRadius: hs(BorderRadius.sm),
    borderWidth: 2,
    borderColor: Colors[theme].borderSecondary,
    marginRight: hs(Spacing.sm),
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: Colors[theme].primary,
    borderColor: Colors[theme].primary,
  },
  checkmark: {
    color: Colors[theme].textInverse,
    fontSize: getFontSize(12),
    fontWeight: 'bold',
  },
  checkboxLabel: {
    fontSize: getFontSize(Typography.bodyMedium.fontSize),
    color: Colors[theme].textSecondary,
    lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
    flexShrink: 1,
  },
  forgotPassword: {
    fontSize: getFontSize(Typography.labelMedium.fontSize),
    color: Colors[theme].link,
    fontWeight: Typography.labelMedium.fontWeight as '500',
    lineHeight: getFontSize(Typography.labelMedium.lineHeight),
    letterSpacing: Typography.labelMedium.letterSpacing,
    paddingVertical: vs(Spacing.sm),
    paddingHorizontal: hs(Spacing.xs),
  },
  loginButton: {
    backgroundColor: Colors[theme].buttonPrimary,
    borderRadius: hs(BorderRadius.md),
    paddingVertical: vs(14),
    alignItems: 'center',
    marginBottom: vs(Spacing.lg),
    minHeight: Math.max(MIN_TOUCH_SIZE, vs(48)),
    justifyContent: 'center',
  },
  loginButtonDisabled: {
    backgroundColor: Colors[theme].buttonPrimaryDisabled,
  },
  loginButtonText: {
    color: Colors[theme].buttonPrimaryText,
    fontSize: getFontSize(Typography.button.fontSize),
    fontWeight: Typography.button.fontWeight as '600',
    lineHeight: getFontSize(Typography.button.lineHeight),
    letterSpacing: Typography.button.letterSpacing,
  },
  signupRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
    minHeight: MIN_TOUCH_SIZE,
  },
  signupText: {
    fontSize: getFontSize(Typography.bodyMedium.fontSize),
    color: Colors[theme].textTertiary,
    lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
  },
  signupLink: {
    fontSize: getFontSize(Typography.labelMedium.fontSize),
    color: Colors[theme].success,
    fontWeight: Typography.labelMedium.fontWeight as '500',
    lineHeight: getFontSize(Typography.labelMedium.lineHeight),
    letterSpacing: Typography.labelMedium.letterSpacing,
    paddingVertical: vs(Spacing.sm),
    paddingHorizontal: hs(Spacing.xs),
  },
})
