import { StyleSheet } from 'react-native'
import {
  wp,
  hp,
  hs,
  vs,
  getSafePadding,
  getFontSize,
  MIN_TOUCH_SIZE,
} from '@/libs/utils'
import { Colors } from '@/libs/constants/theme'

export const createStyles = (theme: 'light' | 'dark') => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors[theme].backgroundSecondary,
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: getSafePadding(),
    paddingVertical: vs(20),
    minHeight: hp(100),
  },
  loginCard: {
    backgroundColor: Colors[theme].surface,
    borderRadius: hs(16),
    paddingHorizontal: getSafePadding(),
    paddingVertical: vs(24),
    shadowColor: Colors[theme].shadowColor,
    shadowOffset: {
      width: 0,
      height: vs(2),
    },
    shadowOpacity: 0.1,
    shadowRadius: hs(8),
    elevation: 5,
    width: '100%',
    maxWidth: wp(90),
    alignSelf: 'center',
  },
  title: {
    fontSize: getFontSize(20),
    fontWeight: '600',
    color: Colors[theme].text,
    textAlign: 'center',
    marginBottom: vs(24),
    lineHeight: getFontSize(28),
  },
  formGroup: {
    marginBottom: vs(16),
  },
  label: {
    fontSize: getFontSize(14),
    fontWeight: '500',
    color: Colors[theme].textSecondary,
    marginBottom: vs(8),
    lineHeight: getFontSize(20),
  },
  input: {
    backgroundColor: Colors[theme].inputBackground,
    borderRadius: hs(8),
    paddingHorizontal: hs(16),
    paddingVertical: vs(12),
    fontSize: getFontSize(16),
    color: Colors[theme].inputText,
    borderWidth: 1,
    borderColor: Colors[theme].inputBorder,
    minHeight: Math.max(MIN_TOUCH_SIZE, vs(48)),
    textAlignVertical: 'center',
    lineHeight: getFontSize(22),
  },
  optionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: vs(24),
    minHeight: MIN_TOUCH_SIZE,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingVertical: vs(8),
  },
  checkbox: {
    width: hs(18),
    height: hs(18),
    borderRadius: hs(3),
    borderWidth: 2,
    borderColor: Colors[theme].borderSecondary,
    marginRight: hs(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: Colors[theme].primary,
    borderColor: Colors[theme].primary,
  },
  checkmark: {
    color: Colors[theme].textInverse,
    fontSize: getFontSize(12),
    fontWeight: 'bold',
  },
  checkboxLabel: {
    fontSize: getFontSize(14),
    color: Colors[theme].textSecondary,
    lineHeight: getFontSize(20),
    flexShrink: 1,
  },
  forgotPassword: {
    fontSize: getFontSize(14),
    color: Colors[theme].link,
    fontWeight: '500',
    lineHeight: getFontSize(20),
    paddingVertical: vs(8),
    paddingHorizontal: hs(4),
  },
  loginButton: {
    backgroundColor: Colors[theme].buttonPrimary,
    borderRadius: hs(8),
    paddingVertical: vs(14),
    alignItems: 'center',
    marginBottom: vs(16),
    minHeight: Math.max(MIN_TOUCH_SIZE, vs(48)),
    justifyContent: 'center',
  },
  loginButtonDisabled: {
    backgroundColor: Colors[theme].buttonPrimaryDisabled,
  },
  loginButtonText: {
    color: Colors[theme].buttonPrimaryText,
    fontSize: getFontSize(16),
    fontWeight: '600',
    lineHeight: getFontSize(22),
  },
  signupRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
    minHeight: MIN_TOUCH_SIZE,
  },
  signupText: {
    fontSize: getFontSize(14),
    color: Colors[theme].textTertiary,
    lineHeight: getFontSize(20),
  },
  signupLink: {
    fontSize: getFontSize(14),
    color: Colors[theme].success,
    fontWeight: '500',
    lineHeight: getFontSize(20),
    paddingVertical: vs(8),
    paddingHorizontal: hs(4),
  },
})
