import { StyleSheet } from 'react-native'
import {
  wp,
  hp,
  vs,
  hs,
  getSafePadding,
  getFontSize,
  MIN_TOUCH_SIZE,
} from '@/libs/utils'
import { Colors } from '@/libs/constants/theme'

export const createStyles = (theme: 'light' | 'dark') => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors[theme].backgroundSecondary,
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: getSafePadding(),
    paddingVertical: vs(20),
    minHeight: hp(100),
  },
  registerCard: {
    backgroundColor: Colors[theme].surface,
    borderRadius: hs(16),
    paddingHorizontal: getSafePadding(),
    paddingVertical: vs(24),
    shadowColor: Colors[theme].shadowColor,
    shadowOffset: {
      width: 0,
      height: vs(2),
    },
    shadowOpacity: 0.1,
    shadowRadius: hs(8),
    elevation: 5,
    width: '100%',
    maxWidth: wp(90),
    alignSelf: 'center',
  },
  title: {
    fontSize: getFontSize(20),
    fontWeight: '600',
    color: Colors[theme].text,
    textAlign: 'center',
    marginBottom: vs(24),
    lineHeight: getFontSize(28),
  },
  formGroup: {
    marginBottom: vs(16),
  },
  label: {
    fontSize: getFontSize(14),
    fontWeight: '500',
    color: Colors[theme].textSecondary,
    marginBottom: vs(8),
    lineHeight: getFontSize(20),
  },
  input: {
    backgroundColor: Colors[theme].inputBackground,
    borderRadius: hs(8),
    paddingHorizontal: hs(16),
    paddingVertical: vs(12),
    fontSize: getFontSize(16),
    color: Colors[theme].inputText,
    borderWidth: 1,
    borderColor: Colors[theme].inputBorder,
    minHeight: Math.max(MIN_TOUCH_SIZE, vs(48)),
    textAlignVertical: 'center',
    lineHeight: getFontSize(22),
  },
  inputError: {
    borderColor: Colors[theme].error,
    borderWidth: 1.5,
  },
  warningText: {
    fontSize: getFontSize(12),
    color: Colors[theme].error,
    marginTop: vs(4),
    marginLeft: hs(4),
    lineHeight: getFontSize(16),
  },
  registerButton: {
    backgroundColor: Colors[theme].buttonPrimary,
    borderRadius: hs(8),
    paddingVertical: vs(14),
    alignItems: 'center',
    marginBottom: vs(16),
    marginTop: vs(8),
    minHeight: Math.max(MIN_TOUCH_SIZE, vs(48)),
    justifyContent: 'center',
  },
  registerButtonDisabled: {
    backgroundColor: Colors[theme].buttonPrimaryDisabled,
  },
  registerButtonText: {
    color: Colors[theme].buttonPrimaryText,
    fontSize: getFontSize(16),
    fontWeight: '600',
    lineHeight: getFontSize(22),
  },
  loginRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
    minHeight: MIN_TOUCH_SIZE,
  },
  loginText: {
    fontSize: getFontSize(14),
    color: Colors[theme].textTertiary,
    lineHeight: getFontSize(20),
  },
  loginLink: {
    fontSize: getFontSize(14),
    color: Colors[theme].link,
    fontWeight: '500',
    lineHeight: getFontSize(20),
    paddingVertical: vs(8),
    paddingHorizontal: hs(4),
  },
})
