import { StyleSheet } from 'react-native'
import {
  hs,
  vs,
  getFontSize,
  MIN_TOUCH_SIZE,
} from '@/libs/utils'
import {
  Colors,
  Typography,
  Spacing,
  BorderRadius,
  Elevation,
  Palette,
} from '@/libs/constants/theme'

export const createStyles = (theme: 'light' | 'dark') => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors[theme].background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: hs(Spacing.lg),
    paddingVertical: vs(Spacing.md),
    backgroundColor: Colors[theme].surface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors[theme].border,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatar: {
    width: hs(36),
    height: hs(36),
    borderRadius: hs(18),
    backgroundColor: '#F4E4C1',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: hs(Spacing.md),
  },
  avatarText: {
    color: '#8B7355',
    fontSize: getFontSize(Typography.labelLarge.fontSize),
    fontWeight: Typography.labelLarge.fontWeight,
  },
  headerTitle: {
    fontSize: getFontSize(Typography.h1.fontSize),
    fontWeight: Typography.h1.fontWeight,
    color: Colors[theme].text,
    lineHeight: getFontSize(Typography.h1.lineHeight),
    letterSpacing: Typography.h1.letterSpacing,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    padding: hs(Spacing.sm),
    marginLeft: hs(Spacing.xs),
    minHeight: MIN_TOUCH_SIZE,
    minWidth: MIN_TOUCH_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: hs(Spacing.lg),
    paddingVertical: vs(Spacing.sm),
    backgroundColor: Colors[theme].inputBackground,
    borderRadius: hs(BorderRadius.md),
    marginHorizontal: hs(Spacing.lg),
    marginTop: vs(Spacing.sm),
  },
  searchIcon: {
    marginRight: hs(Spacing.sm),
  },
  searchInput: {
    flex: 1,
    fontSize: getFontSize(Typography.bodyLarge.fontSize),
    color: Colors[theme].inputText,
  },
  microsoftTeamsIcon: {
    width: hs(20),
    height: hs(20),
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  teamsSquare: {
    width: hs(8),
    height: hs(8),
    margin: hs(1),
  },
  filterContainer: {
    flexDirection: 'row',
    paddingHorizontal: hs(Spacing.screenPadding),
    paddingVertical: vs(Spacing.sm),
    backgroundColor: Colors[theme].surface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors[theme].border,
    gap: hs(Spacing.sm),
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: hs(Spacing.md),
    paddingVertical: vs(Spacing.sm),
    borderRadius: BorderRadius.round,
    backgroundColor: Colors[theme].backgroundSecondary,
  },
  activeFilterButton: {
    backgroundColor: Colors[theme].primary,
  },
  filterText: {
    ...Typography.bodySmall,
    color: Colors[theme].textSecondary,
    fontWeight: '500',
    marginLeft: hs(Spacing.xs),
  },
  activeFilterText: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  conversationsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: hs(Spacing.lg),
    paddingVertical: vs(Spacing.sm),
    backgroundColor: Colors[theme].surface,
  },
  conversationsTitle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  conversationsTitleText: {
    fontSize: getFontSize(Typography.h4.fontSize),
    fontWeight: Typography.h4.fontWeight,
    color: Colors[theme].text,
    marginLeft: hs(Spacing.xs),
    lineHeight: getFontSize(Typography.h4.lineHeight),
    letterSpacing: Typography.h4.letterSpacing,
  },
  moreButton: {
    padding: hs(Spacing.xs),
    minHeight: MIN_TOUCH_SIZE,
    minWidth: MIN_TOUCH_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  conversationsList: {
    flex: 1,
    backgroundColor: Colors[theme].background,
  },
  seeMoreButton: {
    paddingVertical: vs(Spacing.lg),
    backgroundColor: Colors[theme].surface,
    alignItems: 'center',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Colors[theme].border,
    minHeight: MIN_TOUCH_SIZE,
  },
  seeMoreText: {
    fontSize: getFontSize(Typography.labelMedium.fontSize),
    color: Palette.brand[600],
    fontWeight: Typography.labelMedium.fontWeight,
    letterSpacing: Typography.labelMedium.letterSpacing,
  },
  newChatButton: {
    position: 'absolute',
    bottom: vs(32),
    right: hs(Spacing.lg),
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Palette.brand[600],
    paddingHorizontal: hs(18),
    paddingVertical: vs(14),
    borderRadius: hs(28),
    ...Elevation.md,
    minHeight: MIN_TOUCH_SIZE,
  },
  newChatText: {
    color: Colors[theme].textInverse,
    fontSize: getFontSize(Typography.labelMedium.fontSize),
    fontWeight: Typography.labelMedium.fontWeight,
    marginLeft: hs(Spacing.sm),
    letterSpacing: Typography.labelMedium.letterSpacing,
  },
})
