import { StyleSheet } from 'react-native'
import {
  hs,
  vs,
  getFontSize,
  MIN_TOUCH_SIZE,
} from '@/libs/utils'
import {
  Colors,
  Typography,
  Spacing,
  BorderRadius,
  Palette,
} from '@/libs/constants/theme'

export const createStyles = (theme: 'light' | 'dark') => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors[theme].background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: hs(Spacing.lg),
    paddingVertical: vs(Spacing.md),
    borderBottomWidth: 1,
    borderBottomColor: Colors[theme].border,
    backgroundColor: Colors[theme].surface,
  },
  backButton: {
    padding: hs(Spacing.sm),
    marginRight: hs(Spacing.sm),
    minHeight: MIN_TOUCH_SIZE,
    minWidth: MIN_TOUCH_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contactInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  contactAvatar: {
    width: hs(40),
    height: hs(40),
    borderRadius: hs(20),
    backgroundColor: Colors[theme].success,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: hs(Spacing.md),
    position: 'relative',
  },
  contactAvatarText: {
    color: Colors[theme].textInverse,
    fontSize: getFontSize(Typography.labelLarge.fontSize),
    fontWeight: Typography.labelLarge.fontWeight,
  },
  onlineIndicator: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: hs(12),
    height: hs(12),
    borderRadius: hs(6),
    backgroundColor: Colors[theme].warning,
    borderWidth: 2,
    borderColor: Colors[theme].surface,
  },
  contactDetails: {
    flex: 1,
  },
  contactName: {
    fontSize: getFontSize(Typography.h4.fontSize),
    fontWeight: Typography.labelLarge.fontWeight,
    color: Colors[theme].text,
    lineHeight: getFontSize(Typography.h4.lineHeight),
  },
  lastSeen: {
    fontSize: getFontSize(Typography.caption.fontSize),
    color: Colors[theme].textSecondary,
    marginTop: vs(2),
    lineHeight: getFontSize(Typography.caption.lineHeight),
  },
  headerActions: {
    flexDirection: 'row',
  },
  actionButton: {
    padding: hs(Spacing.sm),
    marginLeft: hs(Spacing.sm),
    minHeight: MIN_TOUCH_SIZE,
    minWidth: MIN_TOUCH_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  messagesContainer: {
    flex: 1,
    paddingHorizontal: hs(Spacing.lg),
  },
  dateHeader: {
    alignItems: 'center',
    marginVertical: vs(Spacing.lg),
  },
  dateHeaderText: {
    fontSize: getFontSize(Typography.caption.fontSize),
    color: Colors[theme].textSecondary,
    textAlign: 'center',
    lineHeight: getFontSize(Typography.caption.lineHeight),
  },
  messageContainer: {
    marginVertical: vs(2),
  },
  sentMessageContainer: {
    alignItems: 'flex-end',
  },
  receivedMessageContainer: {
    alignItems: 'flex-start',
  },
  messageBubble: {
    maxWidth: '80%',
    borderRadius: hs(BorderRadius.lg),
    paddingHorizontal: hs(Spacing.md),
    paddingVertical: vs(Spacing.sm),
  },
  sentMessage: {
    backgroundColor: Palette.brand[600],
    borderBottomRightRadius: hs(BorderRadius.sm),
  },
  receivedMessage: {
    backgroundColor: Colors[theme].backgroundTertiary,
    borderBottomLeftRadius: hs(BorderRadius.sm),
  },
  messageText: {
    fontSize: getFontSize(Typography.bodyLarge.fontSize),
    lineHeight: getFontSize(Typography.bodyLarge.lineHeight),
  },
  sentMessageText: {
    color: Colors[theme].textInverse,
  },
  receivedMessageText: {
    color: Colors[theme].text,
  },
  attachmentContainer: {
    marginTop: vs(Spacing.sm),
  },
  attachmentPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors[theme].surface,
    borderRadius: hs(BorderRadius.md),
    padding: hs(Spacing.md),
  },
  documentIcon: {
    width: hs(32),
    height: hs(32),
    backgroundColor: Palette.brand[700],
    borderRadius: hs(BorderRadius.sm),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: hs(Spacing.md),
  },
  documentIconText: {
    color: Colors[theme].textInverse,
    fontSize: getFontSize(Typography.labelMedium.fontSize),
    fontWeight: Typography.labelMedium.fontWeight,
  },
  attachmentInfo: {
    flex: 1,
  },
  attachmentName: {
    fontSize: getFontSize(Typography.bodyMedium.fontSize),
    fontWeight: Typography.labelMedium.fontWeight,
    color: Colors[theme].text,
    lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
  },
  attachmentSize: {
    fontSize: getFontSize(Typography.caption.fontSize),
    color: Colors[theme].textSecondary,
    marginTop: vs(2),
    lineHeight: getFontSize(Typography.caption.lineHeight),
  },
  attachmentMenu: {
    padding: hs(Spacing.xs),
    minHeight: MIN_TOUCH_SIZE,
    minWidth: MIN_TOUCH_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  messageStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingHorizontal: hs(Spacing.lg),
    paddingTop: vs(Spacing.xs),
    paddingBottom: vs(Spacing.sm),
  },
  statusIcon: {
    marginRight: hs(Spacing.xs),
  },
  statusText: {
    fontSize: getFontSize(11),
    color: Colors[theme].textSecondary,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: hs(Spacing.lg),
    paddingVertical: vs(Spacing.md),
    borderTopWidth: 1,
    borderTopColor: Colors[theme].border,
    backgroundColor: Colors[theme].surface,
  },
  attachButton: {
    padding: hs(Spacing.sm),
    marginRight: hs(Spacing.sm),
    minHeight: MIN_TOUCH_SIZE,
    minWidth: MIN_TOUCH_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: Colors[theme].inputBorder,
    borderRadius: hs(BorderRadius.round),
    paddingHorizontal: hs(Spacing.lg),
    paddingVertical: vs(Spacing.sm),
    maxHeight: vs(100),
    fontSize: getFontSize(Typography.bodyLarge.fontSize),
    color: Colors[theme].inputText,
  },
  sendButton: {
    padding: hs(Spacing.sm),
    marginLeft: hs(Spacing.sm),
    minHeight: MIN_TOUCH_SIZE,
    minWidth: MIN_TOUCH_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // File upload styles
  filePreviewContainer: {
    paddingHorizontal: hs(Spacing.lg),
    paddingVertical: vs(Spacing.md),
    borderTopWidth: 1,
    borderTopColor: Colors[theme].border,
    backgroundColor: Colors[theme].backgroundSecondary,
  },
  filePreview: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors[theme].surface,
    borderRadius: hs(BorderRadius.md),
    padding: hs(Spacing.md),
    borderWidth: 1,
    borderColor: Colors[theme].border,
  },
  fileInfo: {
    flex: 1,
    marginLeft: hs(Spacing.md),
  },
  fileName: {
    fontSize: getFontSize(Typography.bodyMedium.fontSize),
    fontWeight: Typography.labelMedium.fontWeight,
    color: Colors[theme].text,
    lineHeight: getFontSize(Typography.bodyMedium.lineHeight),
  },
  fileSize: {
    fontSize: getFontSize(Typography.caption.fontSize),
    color: Colors[theme].textSecondary,
    marginTop: vs(2),
    lineHeight: getFontSize(Typography.caption.lineHeight),
  },
  removeFileButton: {
    padding: hs(Spacing.xs),
    marginLeft: hs(Spacing.sm),
    minHeight: MIN_TOUCH_SIZE,
    minWidth: MIN_TOUCH_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  uploadProgress: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: vs(Spacing.sm),
    paddingHorizontal: hs(Spacing.md),
  },
  uploadText: {
    fontSize: getFontSize(Typography.caption.fontSize),
    color: Colors[theme].textSecondary,
    marginLeft: hs(Spacing.sm),
    lineHeight: getFontSize(Typography.caption.lineHeight),
  },
})
